/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconHeroiconsArchiveBox: typeof import('~icons/heroicons/archive-box')['default']
    IconHeroiconsBookmarkSolid: typeof import('~icons/heroicons/bookmark-solid')['default']
    IconHeroiconsDocumentText: typeof import('~icons/heroicons/document-text')['default']
    IconHeroiconsExclamationTriangle: typeof import('~icons/heroicons/exclamation-triangle')['default']
    IconHeroiconsMagnifyingGlass: typeof import('~icons/heroicons/magnifying-glass')['default']
    IconHeroiconsPencil: typeof import('~icons/heroicons/pencil')['default']
    IconHeroiconsPlus: typeof import('~icons/heroicons/plus')['default']
    IconHeroiconsTag: typeof import('~icons/heroicons/tag')['default']
    IconHeroiconsTrash: typeof import('~icons/heroicons/trash')['default']
    IconHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NoteCard: typeof import('./src/components/NoteCard.vue')['default']
    NoteModal: typeof import('./src/components/NoteModal.vue')['default']
    NotificationContainer: typeof import('./src/components/NotificationContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsAside: typeof import('./src/components/TagsAside.vue')['default']
  }
}
